### PR TITLE
doc / fix links 

### PR DESCRIPTION
**Pull request by rapcmia**
Removed "app" and modify the "TIP" on " Enabling Tether USDT to your Algorand..." in /faq/liquidity-mining/
Fix link for "What's eagle club" on /miner/eagle-club/
Fix link for Cross Exchange Market Making on /faq/market-making.mdx
Fix link for Active campaign on /faq/liquidity-mining/

### CODE REVIEW

**Comment by rapcmia** [comment]
image

image

image

image

**Comment by dennisocana** [comment]
@rapcmia please resolve conflicting files so we can merge.

**Review by carlolm — CHANGES_REQUESTED** [review]
@rapcmia you need to fix merge conflicts

**Comment by rapcmia** [comment]
Fixed merge conflicts

**Review by dennisocana — APPROVED** [review]

**Pull request merged**
